# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a18d915d9f56e82482f4abd43b6ab48c8b90b45d287791db35a25756e56a4fcd44d3796fe8b7690233bd00650784605e98a8a862388c64b7bc460717a4ef95

test:
  secret_key_base: bed577e516ea71b74ec6b8b717673b2d3511d4293644f406df27c18acb777adfec723efcca2c9b9eb59d0f45df063db32a8d8da4a6b92121949d5a2d3e79fc6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
